[package]
name = "zola_page_date_setter"
version = "0.1.0"
description = "Tool to set dates for zola pages based on git history"
keywords = []
repository = "https://github.com/c-git/zola_page_date_setter"
documentation = "https://github.com/c-git/zola_page_date_setter"
categories = []
authors = ["One <one.bgz1@gmailcom>"]
readme = "README.md"
license = "MIT OR Apache-2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
