name: Check Semver

on:
  push: 
    branches:
      - main
  pull_request: 
    branches:
      - main
env:
  CARGO_TERM_COLOR: always

  
jobs:
  semver-checks:
    runs-on: ubuntu-latest
    steps:
      - name: checkout@main
        uses: wykies/checkout@main
      - name: Check semver
        uses: obi1kenobi/cargo-semver-checks-action@main